[package]
name = "wasm"
version = "0.1.0"
authors = ["Shaan Yadav"]
description = "A sample project with wasm-pack"
license = "Apache-2.0"
repository = "https://github.com/shaan106"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"